paths:
  path_gadi_CODA: "/g/data/es60/users/thomas_moore/CODA/"
  path_tube_CODA: "/oa-decadal-climate/work/observations/CARSv2_ancillary/CODA/CODAv1/"
  path_tube_logs: "/oa-decadal-climate/work/moo270/logs/"